server:
  build: .
#  extends:
#    file: ../base-service.yml
#    service: common
#  command: cfrun /startApp.sh
#  privileged: true
#  net: host
  ports:
    - 4999:80
#  environment:
#    - CONTEXT_PATH=/showdoc
  volumes:
    - /data/volumes/showdocdb:/showdoc/Sqlite
#    - /showdoc/Public/Uploads
#    - /showdoc/Application/Common/Conf
#    - /showdoc/Application/Home/Conf
#    - /showdoc/Application/Runtime
#    - /showdoc/server/Application/Runtime 
#    - /showdoc/install 
